### ISSUE TITLE
add host error

### ISSUE THREAD

**Issue by tinglany** [yeasy/cello-archived#5]
when I add host in Cello Dashboard, the worke-node log like this:

ERRO[5899] Handler for POST /v1.30/networks/create returned error: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-2879c5ae5d36 -j RETURN: iptables: No chain/target/match by that name.

**Comment by yeasy** [comment]
@tinglany Pls try the latest code at github.com/hyperledger/cello.

Thanks!
